# fly.toml app configuration file generated for product-personalize on 2024-01-16T13:50:28+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "product-personalize"
primary_region = "lax"

[env] 
  PORT = "3000"
  SHOPIFY_APP_URL = "https://product-personalize.fly.dev/"
  SHOPIFY_API_KEY = "45f0330e50c8c2f1643d410463277fc5"
  SCOPES = "write_products,write_script_tags,read_products"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
